### ISSUE TITLE
Branch de testing

### ISSUE THREAD

**Issue by ferminrp** [ferminrp/meli-to-usdt#10]
Consulta ... ustedes entienden mas que yo de esto.

Deberiamos tener una branch que no sea main para testear y vamos pasando a main solo cuando vamos a pushear una nueva version al store?

**Comment by MateoCerquetella** [comment]
@ferminrp: Si, lo ideal siempre es dejar el branch "main" intacto y crear un branch llamado "develop" donde desde este crearemos nuevos branchs para hacer features. Te dejo una imagen así lo entendes mejor!

![02 Feature branches](https://user-images.githubusercontent.com/33433649/157694911-88c41fba-002b-40a7-9faa-05557db3cc2a.svg)

**Comment by andresgardiol** [comment]
Coincido con lo del branch "develop" pero creo es mejor salir siempre desde "main", ya que develop es una rama inestable.
Por lo tanto, nunca mergeamos develop con main

**Comment by ferminrp** [comment]
A ver si la cazo ... vamos mergeando siempre a develop. 
Cuando estamos para sacar un release lo mergeamos con main o lo mandamos a una branch de esa version para testear con esa?

**Comment by ferminrp** [comment]
develop creada y el ultimo pr mergeado a esa

**Comment by juansegnana** [comment]
> A ver si la cazo ... vamos mergeando siempre a develop. 
> Cuando estamos para sacar un release lo mergeamos con main o lo mandamos a una branch de esa version para testear con esa?

Si puede ser así. La otra es ir haciendo los fixes o features en branches únicas (ej. `fix/cents`), después solo se mergea a main cuando está todo ok.
