### ISSUE TITLE
Hay que eliminar los centavos chiquitos

### ISSUE THREAD

**Issue by ferminrp** [ferminrp/meli-to-usdt#4]
Al momento de hacer la conversion hay un span de centavos que no estamos eliminando

![image](https://user-images.githubusercontent.com/21282919/157438489-4452e78c-e905-4cea-babc-ab99df863ae6.png)

**Comment by MateoCerquetella** [comment]
Con la función removeElement("nombre-de-la-clase") se puede fixear fácilmente, cuando tenga tiempito lo hago sin problemas
