### ISSUE TITLE
Refactorizar Projecto: JavaScript -> TypeScript

### ISSUE THREAD

**Issue by MateoCerquetella** [ferminrp/meli-to-usdt#7]
Buenas a todos como andan? 😁😁

Para cortar semana hago este Spike para hablar los beneficios de refactorizar JavaScript a Typescript,
Vamos a poder implementar OOO y separar cada archivo creando su única funcionalidad como debería ser,
Esta es una list de porque nos serviría a la hora de codear:

> - Te da una muestra del futuro de JavaScript, con elementos tipados.
> - Te ayuda a implementar patrones de diseño SOLID a un lenguaje que no lo soporte.
> - Hace que el código se entienda mejor. El desarrollador reconoce más rápidamente la función de cada código.
> - Una de las mejores ventajas de Typescript es la finalización del código y IntelliSense. Te ayuda a completar tu código a medida que está escrito.
> - Código limpio. La escritura Estática es una característica que detecta errores de les desarrolladores. Promueve que se escriba un lenguaje más robusto y fácil de mantener. Por lo que es un lenguaje más limpio.
> - Puedes escribir fácilmente código orientado a objetos sin mucho conocimiento.
> - El refactoring con las herramientas de Typescript es mucho más fácil y rápido.

Yo prefiero 100% TypeScript a la hora de generar código cuando se tiene que usar obviamente, 
Este es un espacio para discutir como todo open source, avísame @ferminrp como lo ves vos que sos el owner del repo.

Saludos!!

**Comment by ferminrp** [comment]
Yo no soy dev ... apenas se un poquito de lo basico y suelo usar svelte pelado sin nada. Si el resto de los que estan sumando codigo se sienten comodos con typescript le damos para adelante.

@juansegnana @andresgardiol 

Tambien, el que quiera colaborator me avisa. A mi esto me empieza a quedar grande.

**Comment by andresgardiol** [comment]
Re contra a favor de typescript!

**Comment by MateoCerquetella** [comment]
Buenisimo, entonces cuando tenga un tiempito libre voy a refactorizar esto.

Aca encontre un par de ejemplos para seguir:

- https://betterprogramming.pub/creating-chrome-extensions-with-typescript-914873467b65
- https://github.com/chibat/chrome-extension-typescript-starter
- https://blog.logrocket.com/creating-chrome-extension-react-typescript/
